import { useEffect, useState } from 'react';
import { type Elder, HealthInsightTestRunListSchema, HealthInsightTestRunSchema, type HealthInsightTestRun } from '../../schemas';
import { SERVER_URL, authFetch, errMsg } from '../../utils/api';

const topicLabel:Record<string,string>={meal:'식사',sleep:'수면',activity:'활동',discomfort:'불편 사항'};
const valueLabel:Record<string,string>={present:'문제 확인',absent:'현재 문제 없음',unclear:'판단 보류',not_asked:'질문 없음',recognition_failed:'인식 실패'};
const sample='영실이: 오늘 식사와 잠, 활동은 어떠셨어요? 아프거나 불편한 곳은 없으세요?\n어르신: 오늘은 입맛이 없어서 밥을 못 먹었고, 잠도 거의 못 잤어요.';

export default function HealthSyntheticTestPanel({elders,notify}:{elders:Elder[];notify?:(message:string,tone?:string)=>void}){
  const key=(elder:Elder)=>String(elder.phone||elder.id||'');
  const [open,setOpen]=useState(false),[elderId,setElderId]=useState(''),[transcript,setTranscript]=useState(sample);
  const [busy,setBusy]=useState(false),[runs,setRuns]=useState<HealthInsightTestRun[]>([]),[preview,setPreview]=useState<HealthInsightTestRun|null>(null);
  useEffect(()=>{if(!elderId&&elders.length)setElderId(key(elders[0]))},[elders,elderId]);
  const load=async()=>{try{const response=await authFetch(`${SERVER_URL}/health/insights/test-runs`),data:unknown=await response.json();if(!response.ok)throw new Error(errMsg(data));const parsed=HealthInsightTestRunListSchema.safeParse(data);if(!parsed.success)throw new Error('테스트 결과 형식이 올바르지 않습니다');setRuns(parsed.data.items)}catch(error:unknown){notify?.(error instanceof Error?error.message:'테스트 결과를 불러오지 못했습니다')}};
  useEffect(()=>{if(open)load()},[open]); // eslint-disable-line react-hooks/exhaustive-deps
  const run=async(save:boolean)=>{if(!elderId){notify?.('테스트할 어르신을 선택해 주세요');return}if(transcript.trim().length<10){notify?.('대화문을 입력해 주세요');return}setBusy(true);try{const response=await authFetch(`${SERVER_URL}/health/insights/test-runs`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({elderId,transcript,save})}),data:unknown=await response.json();if(!response.ok)throw new Error(errMsg(data));const parsed=HealthInsightTestRunSchema.safeParse(data);if(!parsed.success)throw new Error('테스트 분석 응답 형식이 올바르지 않습니다');setPreview(parsed.data);if(save){await load();notify?.('전화 없이 생성한 테스트 결과를 저장했습니다.','success')}}catch(error:unknown){notify?.(error instanceof Error?error.message:'건강 분석 테스트에 실패했습니다')}finally{setBusy(false)}};
  const remove=async(runId:string)=>{const response=await authFetch(`${SERVER_URL}/health/insights/test-runs/${encodeURIComponent(runId)}`,{method:'DELETE'});const data=await response.json().catch(()=>({}));if(!response.ok){notify?.(errMsg(data));return}await load()};
  const clear=async()=>{if(!window.confirm('저장된 합성 테스트 결과를 모두 삭제할까요?'))return;const response=await authFetch(`${SERVER_URL}/health/insights/test-runs`,{method:'DELETE'});const data=await response.json().catch(()=>({}));if(!response.ok){notify?.(errMsg(data));return}setPreview(null);await load()};
  const card=(run:HealthInsightTestRun,stored=false)=><article key={run.runId||'preview'} className="health-test-result"><div className="health-test-result-head"><div><span className="health-test-badge">테스트 데이터</span><b>{elders.find(e=>key(e)===run.elderId)?.name||'이름 미등록'}</b><time>{new Date(run.createdAt).toLocaleString('ko-KR')}</time></div>{stored&&run.runId&&<button type="button" className="btn-secondary" onClick={()=>remove(run.runId!)}>삭제</button>}</div>{run.observations.length?<div className="health-test-observations">{run.observations.map((observation,index)=><div key={`${observation.topic}-${index}`} className={`health-test-observation is-${observation.value}`}><b>{topicLabel[observation.topic]}</b><span>{valueLabel[observation.value]}</span><q>{observation.evidenceExcerpt}</q></div>)}</div>:<p className="health-test-normal">현재 본인의 건강 문제로 확인된 내용이 없습니다.</p>}</article>;
  return <section className="health-test-panel" aria-labelledby="health-test-title"><div className="health-test-panel-head"><div><span className="health-insights-eyebrow">관리자 전용</span><h3 id="health-test-title">전화 없이 건강 분석 테스트</h3><p>합성 대화로 Gemini 판정과 카드 표시를 확인합니다. 실제 통화·과금·건강 통계에는 포함되지 않습니다.</p></div><button type="button" className="btn-secondary" aria-expanded={open} onClick={()=>setOpen(value=>!value)}>{open?'테스트 닫기':'테스트 열기'}</button></div>{open&&<div className="health-test-body"><div className="health-test-form"><label>테스트 대상<select value={elderId} onChange={event=>setElderId(event.target.value)}>{elders.map(elder=><option key={key(elder)} value={key(elder)}>{elder.name||'이름 없음'}</option>)}</select></label><label>합성 통화 대화문<textarea value={transcript} onChange={event=>setTranscript(event.target.value)} rows={7} maxLength={12000}/></label><div className="health-test-actions"><button type="button" className="btn-secondary" disabled={busy} onClick={()=>run(false)}>{busy?'분석 중…':'미리보기'}</button><button type="button" className="btn-primary" disabled={busy} onClick={()=>run(true)}>{busy?'분석 중…':'테스트 결과 저장'}</button>{runs.length>0&&<button type="button" className="btn-danger-outline" disabled={busy} onClick={clear}>전체 테스트 삭제</button>}</div></div>{preview&&<div><h4>방금 분석 결과</h4>{card(preview)}</div>}{runs.length>0&&<div><h4>저장된 테스트 결과 <small>24시간 후 자동 삭제</small></h4><div className="health-test-results">{runs.map(run=>card(run,true))}</div></div>}</div>}</section>;
}
